apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-microservice
  namespace: microservice
  labels:
    app: python-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-microservice
  template:
    metadata:
      labels:
        app: python-microservice
    spec:
      containers:
      - name: python-microservice
        image: acrmicroservicepwc.azurecr.io/python-microservice:main-a923260
        ports:
        - containerPort: 5000
