apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-microservice-ingress
  namespace: microservice
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - pwc-pythontask.northeurope.cloudapp.azure.com
    secretName: pwc-python-cert
  rules:
  - host: pwc-pythontask.northeurope.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: python-microservice-service
            port:
              number: 80
