apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-microservice-ingress
  namespace: microservice
spec:
  ingressClassName: nginx
  rules:
  - host: pwc-pythontask.northeurope.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: python-microservice-service
            port:

              number: 80


