apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-microservice-ingress
  namespace: microservice
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: microservice.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: python-microservice-svc
            port:
              number: 80