apiVersion: v1
kind: Service
metadata:
  name: python-microservice-service
  namespace: microservice
  labels:
    app: python-microservice
spec:
  selector:
    app: python-microservice  
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP